package game

import (
	"fmt"
	"strconv"
)

type positionOutOfBound struct {
	row    int
	column int
}

type valueNotValid struct {
	value int
}

type originalValue struct {
	row    int
	column int
}

func (e *positionOutOfBound) Error() string {
	return fmt.Sprintf("posistion (%d,%d) is out of bounds...", e.row, e.column)
}

func (e *valueNotValid) Error() string {
	return fmt.Sprintf("value %d is not valid try again", e.value)
}

func (e *originalValue) Error() string {
	return fmt.Sprintf("cannot modify an original value generated by the puzzle at position (%d,%d) ", e.row, e.column)
}

func (s *State) PlaceNumber(row int, column int, value int) error {
	if row < 1 || column < 1 || row >= 10 || column >= 10 {
		return &positionOutOfBound{row, column}
	}
	if value < 1 || value >= 10 {
		return &valueNotValid{value}
	}
	i := row - 1
	j := column - 1
	newValue, err := strconv.Atoi(fmt.Sprintf("%d%d", i, j))
	if err != nil {
		panic(err)
	}
	for _, element := range dictOriginalValues {
		if newValue == element {
			return &originalValue{row, column}
		}
	}
	if value == s.SolvedBoard[i][j] {
		s.Board[i][j] = value
		return nil
	}

	return &valueNotValid{value}

}
